import { preload } from 'react-dom';
import manifest from '@/generated/media-manifest.json';
import type { ImageVM } from '@/lib/data';

type Props = {
  image: ImageVM;
  /** Tells the browser the display width, e.g. `(min-width: 64rem) 40vw, 90vw`. */
  sizes: string;
  className?: string;
  /** Set for the main above-the-fold image (LCP): loads eagerly with high priority. */
  priority?: boolean;
};

/**
 * `<picture>` with AVIF + WebP sources generated by `scripts/optimize-images.ts`.
 * Width/height are set so the page doesn't jump while images load.
 */
export function ResponsiveImage({ image, sizes, className, priority = false }: Props) {
  const entry = (
    manifest.images as Record<string, (typeof manifest.images)[keyof typeof manifest.images]>
  )[image.key];
  if (!entry)
    throw new Error(`Image "${image.key}" missing from media manifest. Run \`npm run images\`.`);

  const srcSet = (ext: string) =>
    entry.widths.map((w) => `/media/${image.key}-${w}.${ext} ${w}w`).join(', ');
  const largest = entry.widths[entry.widths.length - 1];

  // The main hero image is announced in <head>, so the browser fetches it before
  // it has parsed the page body (improves LCP).
  if (priority) {
    preload(`/media/${image.key}-${largest}.avif`, {
      as: 'image',
      type: 'image/avif',
      imageSrcSet: srcSet('avif'),
      imageSizes: sizes,
      fetchPriority: 'high',
    });
  }

  return (
    <picture>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet('webp')} sizes={sizes} />
      <img
        src={`/media/${image.key}-${largest}.webp`}
        alt={image.alt}
        width={entry.width}
        height={entry.height}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : 'auto'}
        decoding="async"
        className={className}
        style={{ backgroundColor: entry.color }}
      />
    </picture>
  );
}

export function mediaUrl(key: keyof typeof manifest.images, width?: number): string {
  const entry = manifest.images[key];
  return `/media/${key}-${width ?? entry.widths[entry.widths.length - 1]}.webp`;
}

export const ogImages = manifest.og;
